name: Normal dotnet publish

on:
  push:
    branches: [ "development-(have-not-been-tested)" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # Build
    - name: Create release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./create-release.bat

    # Upload artifact
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: Release-windows7-x64
        path: Release-windows7-x64
        retention-days: 7
